title: Notes on LeetCode
name: Devin Horvay
email: devin.c.horvay@gmail.com
description: >-
  LeetCode solutions in Python 3.10.x
github_username: dhorvay
url: https://dhorvay.github.io
baseurl: /leetcode
minimal_mistakes_skin: default
search: true
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: America/New_York

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name: Stuck on a problem? Here's a guide to help.
  bio: Solutions in Python 3.10.x.
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://dhorvay.github.io/"
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/channel/UCNgHblX15MjNt0oAvozwkBA"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/dhorvay/leetcode/"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      related: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development